const en = {
  common: { loading: "Loading...", noData: "No data.", guest: "Guest", all: "All", home: "Home", away: "Away", season: "Season", round: "Round", venue: "Venue", live: "Live", upcoming: "Upcoming", finished: "Finished" },
  header: { home: "Home", matches: "Matches", teams: "Teams", standings: "Standings", favorites: "Favorites", auth: "Auth", logout: "Logout", guest: "Guest", toggleMenu: "Toggle menu", language: "Language" },
  footer: { description: "Sports web app with matches, teams, standings, favorites and external data integration." },
  matches: { kicker: "Fixtures", title: "Matches", errorLoad: "Failed to load matches.", errorLogin: "Please login first to use favorites.", errorFavorite: "Failed to update favorite match.", searchPlaceholder: "Search by team or tournament...", allSections: "All sections", liveOnly: "Live only", upcomingOnly: "Upcoming only", finishedOnly: "Finished only", newestFirst: "Newest first", oldestFirst: "Oldest first", teamsAZ: "Teams A-Z", highestScore: "Highest score", filteredMatches: "All filtered matches.", liveNow: "Matches that are live now.", scheduled: "Scheduled matches.", finishedDone: "Finished matches.", autoRefresh: "Live auto-refresh", updated: "Updated", liveTitle: "Live Matches", upcomingTitle: "Upcoming Matches", finishedTitle: "Finished Matches", noMatchesInSection: "No matches in this section.", openMatch: "Open match", scorePending: "Score pending sync", grid: "Grid", list: "List", loadingMore: "Loading more matches..." },
  auth: { kicker: "Account", title: "Authentication", welcomeBack: "Welcome back", createAccount: "Create account", signInContinue: "Sign in to continue", startPlatform: "Start using the platform", login: "Login", register: "Register", email: "Email", password: "Password", passwordPlaceholder: "Minimum 6 characters", pleaseWait: "Please wait...", loginSuccess: "Login successful.", registerSuccess: "Registration successful.", error: "Failed to complete authentication request.", loginHint: "Open favorites, save matches and quickly return to your tracked teams.", registerHint: "Create a new account in a few seconds and keep your own football workspace.", matchesHint: "After login you can move between live, upcoming and finished matches without losing your saved items." },
  notFound: { title: "Page not found", subtitle: "This page does not exist or has been moved.", goHome: "Go home", openMatches: "Open matches" },
  home: { loadingDashboard: "Loading dashboard...", noDashboardData: "No dashboard data.", platformKicker: "Sports Analytics Platform", heroTitle: "Real match data, standings, teams and favorites in one place", heroSubtitle: "Platform for football fans with real matches, standings, team pages, favorites and external API synchronization.", exploreMatches: "Explore matches", openStandings: "Open standings", leagueSnapshot: "League snapshot", allLeagues: "All leagues", leagueNotSelected: "League is not selected", liveNowDesc: "Matches that are currently live.", completedDesc: "Completed matches.", scheduledDesc: "Scheduled matches.", loadingLeagueData: "Loading league data...", leagueInsights: "League Insights", fullTable: "Full table", noInsightData: "No standings data available for insights.", leader: "Leader", bestAttack: "Best attack", bestDefense: "Best defense", mostWins: "Most wins", pts: "pts", goalsScored: "goals scored", goalsConceded: "goals conceded", wins: "wins", topStandings: "Top Standings", noStandingsFound: "No standings found.", team: "Team", season: "Season", featuredTeams: "Featured Teams", allTeams: "All teams", noFeaturedTeams: "No featured teams found.", position: "Position", winRate: "Win rate", goals: "Goals", openTeam: "Open team", liveNowTitle: "Live Now", noLiveNow: "No live matches right now.", noUpcoming: "No upcoming matches.", latestResults: "Latest Results", noFinishedYet: "No finished matches yet.", availableSeasons: "Available Seasons", noSeasons: "No seasons found.", tournament: "Tournament", quickNavigation: "Quick Navigation", browseTeams: "Browse teams, details and recent form.", browseMatches: "Match list with filters, details and favorites.", browseFavorites: "Favorite teams and matches for current user." },
  teams: { kicker: "Clubs", title: "Teams", errorLoad: "Failed to load teams.", errorLogin: "Please login first to use favorites.", errorFavorite: "Failed to update favorite team.", searchPlaceholder: "Search by team name, short name or country...", sortName: "Name A-Z", sortWinRate: "Best win rate", sortGoals: "Most goals scored", sortGd: "Best goal difference", loading: "Loading teams...", found: "Found teams", noTeams: "No teams found.", club: "Club", countryMissing: "Country not specified", cleanSheets: "Clean sheets", avgGoals: "Avg goals", played: "Played", winRate: "Win rate", goals: "Goals", gd: "GD", noStats: "No stats available yet.", noDescription: "No description available.", openTeam: "Open team" },
  standings: { errorSeasons: "Failed to load seasons.", errorStandings: "Failed to load standings.", noSeasons: "No seasons", searchTeam: "Search team...", sortPosition: "Sort by position", sortPoints: "Sort by points", sortWins: "Sort by wins", sortGd: "Sort by goal difference", sortTeam: "Sort by team A-Z", loading: "Loading standings...", empty: "No standings found for this selection.", table: "League Table", rows: "Rows" },
  favorites: { noUser: "No logged in user found. Please login first.", errorLoad: "Failed to load favorites.", loginFirst: "Please login first.", errorRemoveTeam: "Failed to remove team from favorites.", errorRemoveMatch: "Failed to remove match from favorites.", loading: "Loading favorites...", goAuth: "Go to auth", favoriteTeams: "Favorite Teams", favoriteMatches: "Favorite Matches", noTeams: "No favorite teams yet.", noMatches: "No favorite matches yet.", remove: "Remove", removing: "Removing...", bestTeam: "Best team", bestTeamHint: "Most stable favorite by current win rate and team stats." },
  matchDetails: { loading: "Loading match details...", errorLoad: "Failed to load match details.", notFound: "Match not found.", kicker: "Match Center", addFav: "Add to favorites", removeFav: "Remove from favorites", back: "Back to matches", info: "Match info", tournament: "Tournament", quickView: "Quick view", openHomeTeam: "Open home team", openAwayTeam: "Open away team", draws: "Draws", h2hHomeWins: "Wins in recent head-to-head matches.", h2hDraws: "Draw results in recent meetings.", h2hAwayWins: "Wins in recent head-to-head matches.", comparison: "Team comparison", comparisonLoading: "Loading comparison stats...", comparisonEmpty: "Comparison stats are not available.", avgGoals: "Avg goals scored", headToHead: "Head-to-head", h2hLoading: "Loading head-to-head...", h2hEmpty: "No previous meetings found.", homeForm: "Home team form", awayForm: "Away team form", formLoading: "Loading recent form...", formEmpty: "No recent matches found.", insightUnavailable: "Comparison insight is not available yet.", insightBalanced: "The matchup looks balanced based on current team stats.", insightHomeEdge: "The home team has a slight statistical edge.", insightAwayEdge: "The away team has a slight statistical edge.", events: "Key player events", eventsLoading: "Loading player events...", eventsEmpty: "No player events available for this match.", unknownPlayer: "Unknown player", event: "EVENT", team: "Team", assist: "Assist" },
  teamDetails: { loading: "Loading team details...", errorLoad: "Failed to load team details.", notFound: "Team not found.", kicker: "Club Profile", subtitle: "Team details and key statistics.", addFav: "Add to favorites", removeFav: "Remove from favorites", backTeams: "Back to teams", overview: "Overview", fullName: "Full name", shortName: "Short name", country: "Country", description: "Description", noDescription: "No description available.", stats: "Team Statistics", statsLoading: "Loading team stats...", noStats: "No team stats available." },
  external: {
    kicker: "External API", standingsTitle: "World Football Standings", loadingStandings: "Loading external standings...", errorStandings: "Failed to load external standings.", noStandings: "No standings found.",
    errorTeamMatches: "Failed to load external team matches.", loadingTeamMatches: "Loading external team matches...", noTeamMatches: "No matches found for this team.",
    importedKicker: "Imported Data", importedTitle: "Imported Matches", importedSubtitle: "Matches already saved in your database after import from external provider.", loadingImported: "Loading imported matches...", errorImported: "Failed to load imported matches.", importToDb: "Import to DB", importing: "Importing...", importDone: "Import completed", imported: "Imported", updated: "updated", total: "total", noImported: "No imported matches found for this competition yet.", errorImport: "Failed to import matches into database.", noDate: "Date not available",
    syncPreparation: "Sync Preparation", competitionMappingTitle: "External Competition Mapping", competitionMappingSubtitle: "Map external competitions to internal seasons for correct sync target.", loadingCompetitionMappings: "Loading competition mappings...", errorCompetitionMappings: "Failed to load competition mapping data.", selectSeasonFirst: "Please select an internal season first.", errorSaveCompetitionMapping: "Failed to save competition mapping.", savedMapping: "Saved mapping", externalCode: "External code", selectInternalSeason: "Select internal season", current: "Current", save: "Save",
    teamMappingTitle: "External Team Mapping", loadingTeamMappings: "Loading team mappings...", errorTeamMappings: "Failed to load team mapping data.", selectTeamFirst: "Please select an internal team first.", errorSaveTeamMapping: "Failed to save team mapping.", deletedMapping: "Deleted mapping for", errorDeleteTeamMapping: "Failed to delete team mapping.", autoMapDone: "Auto-map completed", mapped: "mapped", alreadyMapped: "already mapped", skipped: "skipped", errorAutoMap: "Failed to auto-map teams.", teamsImportDone: "Teams import completed", externalTeams: "External teams", created: "created", alreadyExists: "already existing", errorImportTeams: "Failed to import missing teams.", importingTeams: "Importing teams...", importMissingTeams: "Import missing teams", autoMapping: "Auto-mapping...", autoMapTeams: "Auto-map teams", noExternalTeams: "No external teams found.", externalId: "External ID", selectInternalTeam: "Select internal team", delete: "Delete",
    realSync: "Real Sync", syncTitle: "External Match Sync", errorSyncData: "Failed to load sync data.", syncDone: "Sync completed", refreshed: "refreshed", errorSync: "Failed to sync external matches.", fullSyncDone: "Full sync completed", createdTeams: "Created teams", createdMatches: "Created matches", updatedMatches: "updated matches", errorFullSync: "Failed to run full sync pipeline.", mappedTeams: "Mapped teams", competitionMapping: "Competition mapping", manual: "Manual", targetSeason: "Target season", syncing: "Syncing...", importAndSync: "Import + Sync", runningFullSync: "Running full sync...", fullSyncPipeline: "Full sync pipeline", autoMappingActive: "Auto mapping active", noCompetitionMapping: "No competition mapping found. Manual season selection will be used."
  }
};

export default en;
