const ua = {
  common: { loading: "Завантаження...", noData: "Немає даних.", guest: "Гість", all: "Усі", home: "Дома", away: "В гостях", season: "Сезон", round: "Раунд", venue: "Стадіон", live: "Наживо", upcoming: "Заплановано", finished: "Завершено" },
  header: { home: "Головна", matches: "Матчі", teams: "Команди", standings: "Таблиця", favorites: "Обране", auth: "Вхід", logout: "Вийти", guest: "Гість", toggleMenu: "Відкрити меню", language: "Мова" },
  footer: { description: "Спортивний вебзастосунок з матчами, командами, турнірними таблицями, обраним та зовнішньою інтеграцією даних." },
  matches: { kicker: "Матчі", title: "Матчі", errorLoad: "Не вдалося завантажити матчі.", errorLogin: "Спочатку увійди, щоб працювати з обраним.", errorFavorite: "Не вдалося оновити обраний матч.", searchPlaceholder: "Пошук за командою або турніром...", allSections: "Усі секції", liveOnly: "Лише live", upcomingOnly: "Лише заплановані", finishedOnly: "Лише завершені", newestFirst: "Новіші спочатку", oldestFirst: "Старіші спочатку", teamsAZ: "Команди А-Я", highestScore: "Найбільший рахунок", filteredMatches: "Усі матчі після фільтрації.", liveNow: "Матчі, що тривають зараз.", scheduled: "Заплановані матчі.", finishedDone: "Завершені матчі.", autoRefresh: "Автооновлення live", updated: "Оновлено", liveTitle: "Live матчі", upcomingTitle: "Заплановані матчі", finishedTitle: "Завершені матчі", noMatchesInSection: "У цій секції немає матчів.", openMatch: "Відкрити матч", scorePending: "Рахунок ще синхронізується", grid: "Сітка", list: "Список", loadingMore: "Довантаження матчів..." },
  auth: { kicker: "Акаунт", title: "Авторизація", welcomeBack: "З поверненням", createAccount: "Створити акаунт", signInContinue: "Увійди, щоб продовжити", startPlatform: "Почни користуватися платформою", login: "Увійти", register: "Реєстрація", email: "Email", password: "Пароль", passwordPlaceholder: "Мінімум 6 символів", pleaseWait: "Зачекай...", loginSuccess: "Вхід успішний.", registerSuccess: "Реєстрація успішна.", error: "Не вдалося виконати запит авторизації." },
  notFound: { title: "Сторінку не знайдено", subtitle: "Ця сторінка не існує або була переміщена.", goHome: "На головну", openMatches: "До матчів" },
  home: { loadingDashboard: "Завантаження дашборду...", noDashboardData: "Немає даних дашборду.", platformKicker: "Платформа Sports Analytics", heroTitle: "Реальні матчі, таблиці, команди та обране в одному місці", heroSubtitle: "Платформа для футбольних фанатів з реальними матчами, таблицями, сторінками команд, обраним та синхронізацією зовнішнього API.", exploreMatches: "Перейти до матчів", openStandings: "Відкрити таблицю", leagueSnapshot: "Зріз ліги", allLeagues: "Усі ліги", leagueNotSelected: "Лігу не обрано", liveNowDesc: "Матчі, що тривають зараз.", completedDesc: "Завершені матчі.", scheduledDesc: "Заплановані матчі.", loadingLeagueData: "Завантаження даних ліги...", leagueInsights: "Аналітика ліги", fullTable: "Повна таблиця", noInsightData: "Немає даних таблиці для аналітики.", leader: "Лідер", bestAttack: "Найкраща атака", bestDefense: "Найкращий захист", mostWins: "Найбільше перемог", pts: "очк.", goalsScored: "забито", goalsConceded: "пропущено", wins: "перемог", topStandings: "Топ таблиці", noStandingsFound: "Таблицю не знайдено.", team: "Команда", season: "Сезон", featuredTeams: "Рекомендовані команди", allTeams: "Усі команди", noFeaturedTeams: "Рекомендованих команд не знайдено.", position: "Позиція", winRate: "Відсоток перемог", goals: "Голи", openTeam: "Відкрити команду", liveNowTitle: "Наживо", noLiveNow: "Зараз немає live-матчів.", noUpcoming: "Немає запланованих матчів.", latestResults: "Останні результати", noFinishedYet: "Ще немає завершених матчів.", availableSeasons: "Доступні сезони", noSeasons: "Сезони не знайдено.", tournament: "Турнір", quickNavigation: "Швидка навігація", browseTeams: "Перегляд команд, деталей та останньої форми.", browseMatches: "Список матчів з фільтрами, деталями та обраним.", browseFavorites: "Обрані команди та матчі поточного користувача." },
  teams: { kicker: "Клуби", title: "Команди", errorLoad: "Не вдалося завантажити команди.", errorLogin: "Спочатку увійди, щоб працювати з обраним.", errorFavorite: "Не вдалося оновити обрану команду.", searchPlaceholder: "Пошук за назвою, скороченням або країною...", sortName: "Назва А-Я", sortWinRate: "Найкращий % перемог", sortGoals: "Найбільше забито", sortGd: "Найкраща різниця м'ячів", loading: "Завантаження команд...", found: "Знайдено команд", noTeams: "Команд не знайдено.", club: "Клуб", countryMissing: "Країну не вказано", cleanSheets: "Сухі матчі", avgGoals: "Сер. голи", played: "Зіграно", winRate: "% перемог", goals: "Голи", gd: "РМ", noStats: "Статистика ще недоступна.", noDescription: "Опис відсутній.", openTeam: "Відкрити команду" },
  standings: { errorSeasons: "Не вдалося завантажити сезони.", errorStandings: "Не вдалося завантажити таблицю.", noSeasons: "Немає сезонів", searchTeam: "Пошук команди...", sortPosition: "Сортувати за позицією", sortPoints: "Сортувати за очками", sortWins: "Сортувати за перемогами", sortGd: "Сортувати за різницею м'ячів", sortTeam: "Сортувати за командою А-Я", loading: "Завантаження таблиці...", empty: "Для цього вибору таблицю не знайдено.", table: "Турнірна таблиця", rows: "Рядків" },
  favorites: { noUser: "Користувач не знайдений. Спочатку увійди.", errorLoad: "Не вдалося завантажити обране.", loginFirst: "Спочатку увійди.", errorRemoveTeam: "Не вдалося видалити команду з обраного.", errorRemoveMatch: "Не вдалося видалити матч з обраного.", loading: "Завантаження обраного...", goAuth: "Перейти до входу", favoriteTeams: "Обрані команди", favoriteMatches: "Обрані матчі", noTeams: "Ще немає обраних команд.", noMatches: "Ще немає обраних матчів.", remove: "Видалити", removing: "Видалення..." },
  matchDetails: { loading: "Завантаження деталей матчу...", errorLoad: "Не вдалося завантажити деталі матчу.", notFound: "Матч не знайдено.", kicker: "Центр матчу", addFav: "Додати в обране", removeFav: "Прибрати з обраного", back: "Назад до матчів", events: "Ключові події гравців", eventsLoading: "Завантаження подій гравців...", eventsEmpty: "Для цього матчу подій немає.", unknownPlayer: "Невідомий гравець", event: "ПОДІЯ", team: "Команда", assist: "Асист" },
  teamDetails: { loading: "Завантаження деталей команди...", errorLoad: "Не вдалося завантажити деталі команди.", notFound: "Команду не знайдено.", kicker: "Профіль клубу", subtitle: "Деталі команди та ключова статистика.", addFav: "Додати в обране", removeFav: "Прибрати з обраного", backTeams: "Назад до команд", overview: "Огляд", fullName: "Повна назва", shortName: "Коротка назва", country: "Країна", description: "Опис", noDescription: "Опис відсутній.", stats: "Статистика команди", statsLoading: "Завантаження статистики команди...", noStats: "Статистика команди недоступна." },
  external: {
    kicker: "Зовнішнє API", standingsTitle: "Турнірні таблиці світу", loadingStandings: "Завантаження зовнішньої таблиці...", errorStandings: "Не вдалося завантажити зовнішню таблицю.", noStandings: "Таблицю не знайдено.",
    errorTeamMatches: "Не вдалося завантажити зовнішні матчі команди.", loadingTeamMatches: "Завантаження зовнішніх матчів команди...", noTeamMatches: "Для цієї команди матчів не знайдено.",
    importedKicker: "Імпортовані дані", importedTitle: "Імпортовані матчі", importedSubtitle: "Матчі, які вже збережені у вашій БД після імпорту із зовнішнього провайдера.", loadingImported: "Завантаження імпортованих матчів...", errorImported: "Не вдалося завантажити імпортовані матчі.", importToDb: "Імпортувати в БД", importing: "Імпорт...", importDone: "Імпорт завершено", imported: "Імпортовано", updated: "оновлено", total: "всього", noImported: "Імпортованих матчів для цієї ліги поки немає.", errorImport: "Не вдалося імпортувати матчі в базу даних.", noDate: "Дата недоступна",
    syncPreparation: "Підготовка синхронізації", competitionMappingTitle: "Мапінг зовнішніх ліг", competitionMappingSubtitle: "Зістав зовнішні ліги з внутрішніми сезонами для коректного синку.", loadingCompetitionMappings: "Завантаження мапінгів ліг...", errorCompetitionMappings: "Не вдалося завантажити дані мапінгу ліг.", selectSeasonFirst: "Спочатку оберіть внутрішній сезон.", errorSaveCompetitionMapping: "Не вдалося зберегти мапінг ліги.", savedMapping: "Мапінг збережено", externalCode: "Зовнішній код", selectInternalSeason: "Оберіть внутрішній сезон", current: "Поточний", save: "Зберегти",
    teamMappingTitle: "Мапінг зовнішніх команд", loadingTeamMappings: "Завантаження мапінгів команд...", errorTeamMappings: "Не вдалося завантажити дані мапінгу команд.", selectTeamFirst: "Спочатку оберіть внутрішню команду.", errorSaveTeamMapping: "Не вдалося зберегти мапінг команди.", deletedMapping: "Видалено мапінг для", errorDeleteTeamMapping: "Не вдалося видалити мапінг команди.", autoMapDone: "Автомапінг завершено", mapped: "зіставлено", alreadyMapped: "вже зіставлено", skipped: "пропущено", errorAutoMap: "Не вдалося виконати автомапінг команд.", teamsImportDone: "Імпорт команд завершено", externalTeams: "Зовнішні команди", created: "створено", alreadyExists: "вже існує", errorImportTeams: "Не вдалося імпортувати відсутні команди.", importingTeams: "Імпорт команд...", importMissingTeams: "Імпортувати відсутні команди", autoMapping: "Автомапінг...", autoMapTeams: "Автомапінг команд", noExternalTeams: "Зовнішніх команд не знайдено.", externalId: "Зовнішній ID", selectInternalTeam: "Оберіть внутрішню команду", delete: "Видалити",
    realSync: "Реальна синхронізація", syncTitle: "Синхронізація зовнішніх матчів", errorSyncData: "Не вдалося завантажити дані синхронізації.", syncDone: "Синхронізацію завершено", refreshed: "оновлено", errorSync: "Не вдалося синхронізувати зовнішні матчі.", fullSyncDone: "Повну синхронізацію завершено", createdTeams: "Створено команд", createdMatches: "Створено матчів", updatedMatches: "оновлено матчів", errorFullSync: "Не вдалося виконати повний pipeline.", mappedTeams: "Зіставлені команди", competitionMapping: "Мапінг ліги", manual: "Вручну", targetSeason: "Цільовий сезон", syncing: "Синхронізація...", importAndSync: "Імпорт + синк", runningFullSync: "Виконується повний синк...", fullSyncPipeline: "Повний pipeline синку", autoMappingActive: "Автомапінг активний", noCompetitionMapping: "Мапінг ліги не знайдено. Буде використано ручний вибір сезону."
  }
};

export default ua;
